CREATE DATABASE IF NOT EXISTS kvdb;
CREATE USER IF NOT EXISTS 'kvuser'@'localhost' IDENTIFIED BY 'kvpass';
GRANT ALL PRIVILEGES ON kvdb.* TO 'kvuser'@'localhost';
FLUSH PRIVILEGES;

USE kvdb;

CREATE TABLE IF NOT EXISTS kv_store (
  k VARCHAR(255) PRIMARY KEY,
  v MEDIUMTEXT
) ENGINE=InnoDB;
